### ISSUE TITLE
A window manager is already running on screen 0

### ISSUE THREAD

**Issue by jlssmt** [dtpnk/docker-portfolio#9]
Hello,

I get this errors while starting:

```
portfolio  | [services.d] starting app...
portfolio  | [app] starting DockerApp...
portfolio  | [services.d] done.
portfolio  | Unable to create
portfolio  | /.dbus
portfolio  | Unable to create
portfolio  | /.dbus/session-bus
portfolio  | Openbox-Message: Unable to change to home directory "
portfolio  | ": No such file or directory
portfolio  | Openbox-Message: A window manager is already running on screen 0
portfolio  | [app] starting DockerApp...
portfolio  | Openbox-Message: Unable to change to home directory "
portfolio  | ": No such file or directory
portfolio  | Openbox-Message: A window manager is already running on screen 0
```

I'm using this docker-compose.yaml:
```yaml
services:
  portfolio:
    build:
      context: .
      args:
        - LOCALE="de_DE"
    container_name: portfolio
    restart: unless-stopped
    ports:
      - 5800:5800
    volumes:
      - ./workspace:/opt/portfolio/workspace
    environment:
      - KEEP_APP_RUNNING=1
      - USER_ID=0
      - GROUP_ID=0
      - TZ="Europe/Berlin"
```
